function chng_pic1(){
    document.getElementById("111").src="top_img/top_1.png"; document.getElementById("des_para").innerHTML = "<p><B>A Pink Crop Top</B> can be a trendy and fashionable addition to your wardrobe. Here are some key points to note about pink crop tops:</p>   <ol><li>Color Psychology: Pink is often associated with femininity, sweetness, and charm. Wearing a pink crop top can convey a sense of fun and vibrancy, perfect for casual wear or outings with friends.</li><li>Versatility: Pink crop tops come in various styles, from fitted to loose and flowy. The cropped length adds a playful and youthful touch to your outfit. They can be paired with high-waisted jeans, shorts, skirts, or layered over dresses, making them versatile for different occasions.</li><li>Styling Options: Pink crop tops can be dressed up or down depending on the occasion. A casual cotton crop top is ideal for everyday wear, while a sequined or embellished pink crop top can be perfect for a night out or a special event. Accessories like necklaces can enhance the look.</li></ol>"
}

function chng_pic2(){
    document.getElementById("111").src="top_img/top_2.png"; document.getElementById("des_para").innerHTML = "<p><B>A Lavender Crop Top</B> can be a chic and stylish addition to your wardrobe. Here are some key points to note about lavender crop tops:</p><ol><li>Color Psychology: Lavender is often associated with elegance, grace, and calmness. Wearing a lavender crop top can convey a sense of sophistication and tranquility, making it a versatile choice for various occasions.</li><li>Versatility: Lavender crop tops come in different styles, from fitted to flowy. The cropped length adds a modern and playful element to your outfit. They can be paired with high-waisted jeans, shorts, skirts, or layered under jackets or cardigans.</li><li>Styling Options: Lavender crop tops can be dressed up or down depending on the occasion. A simple lavender crop top can be paired with jeans for a casual look, while a lace or satin lavender crop top can be dressed up with tailored trousers or a skirt for a more formal outfit.</li></ol>"
}

function chng_pic3(){
    document.getElementById("111").src="top_img/top_3.png"; document.getElementById("des_para").innerHTML = "<p><B>A Black Crop Top</B> can be a timeless and versatile addition to your wardrobe. Here are some key points to note about black crop tops:</p><ol><li>Color Psychology: Black is often associated with elegance, sophistication, and mystery. Wearing a black crop top can convey a sense of confidence and style, making it a staple for many fashion enthusiasts.</li><li>Versatility: Black crop tops come in various styles, from simple basics to embellished designs. The cropped length adds a modern and edgy touch to your outfit. They can be paired with high-waisted jeans, skirts, shorts, or layered under jackets or blazers.</li><li>Styling Options: Black crop tops are incredibly versatile and can be dressed up or down for different occasions. A plain black crop top can be paired with jeans or leggings for a casual look, while a sequined or lace black crop top can be worn with tailored pants or a skirt for a night out or special event.</li></ol>"
}

function chng_pic4(){
    document.getElementById("111").src="top_img/top_4.png"; document.getElementById("des_para").innerHTML = "<p><B>A Red Off-Shoulder' Top</B> can be a bold and stylish addition to your wardrobe. Here are some key points to note about red off-shoulder tops:</p> <ol><li>Color Psychology: Red is often associated with passion, confidence, and energy. Wearing a red off-shoulder top can convey a sense of boldness and allure, making it a statement piece.</li><li>Versatility: Red off-shoulder tops come in various styles, from casual to dressy. The off-shoulder design adds a touch of femininity and elegance to your outfit. They can be paired with jeans, shorts, skirts, or layered under jackets or cardigans.</li><li>Styling Options: Red off-shoulder tops are versatile and can be dressed up or down for different occasions. For a casual look, pair it with denim jeans or shorts. For a more formal or evening look, opt for a red off-shoulder top with embellishments or a structured silhouette paired with tailored pants or a skirt.</li></ol>"
}

